# dataset setting
dataset: anet

data_path: "data/anet/" # ripl-w6
# data_path: 'data/anet-nethome/'  # skynet
# data_path: '/srv/datasets/activityNet/anet-entities/'  # skynet
# data_path: "/coc/scratch/cma64/anet-entities/" # skynet
# data_path: '/datasets/cma64/anet/'  # ripl-w1
# data_path: /home/temp/cma64/anet-entities/ # ripl-s1

input_json: "cap_anet_trainval.json"
input_dic: "dic_anet.json"
input_raw_cap: "anet_captions_all_splits.json"
seg_feature_root: "rgb_motion_1d"
feature_root: "fc6_feat_100rois"
proposal_h5: "anet_detection_vg_fc6_feat_100rois.h5"

val_split: validation
densecap_references: ["anet_entities_val_1.json", "anet_entities_val_2.json"]
# use the following two lines for test set submission
# val_split: testing
# densecap_references: ["anet_entities_test_1.json", "anet_entities_test_2.json"]

# training and eval setting
# exp_name: 20190910-cyclical-softattn_additive-resume_roi-BS_96-cpu_8-LR_1e-4-epoch_100-riplw2-seed_123
# exp_name: 20190912-cyclical-softattn_additive-resume_roi-BS_96-cpu_8-LR_1e-4-epoch_100-skynet-seed_50
# exp_name: 20190912-cyclical-softattn_additive-resume_roi-BS_64-cpu_8-LR_1e-4-epoch_100-riplw2-seed_1
#exp_name: 20191111-cyclical-softattn_additive-resume_roi-BS_32-cpu_8-LR_1e-4-epoch_100-riplw6-seed_1
# exp_name: 20191112-cyclical-softattn_additive-localizer_only_groundable-resume_roi-BS_96-cpu_8-LR_1e-4-epoch_100-riplw1-seed_1
# exp_name: 20191113-cyclical-softattn_additive-localizer_only_groundable-resume_roi-BS_96-cpu_8-LR_1e-4-epoch_100-riplw1-seed_50
# exp_name: 20190910-cyclical-softattn_additive-resume_roi-BS_64-cpu_8-LR_1e-4-epoch_100-riplw2-seed_123
# exp_name: 20190910-cyclical-softattn_additive-resume_roi-BS_96-cpu_8-LR_1e-4-epoch_100-skynet-seed_123
# exp_name: 20190910-cyclical-softattn_additive-resume_roi-BS_96-cpu_8-LR_1e-4-epoch_100-skynet-seed_1
# exp_name: 20190910-cyclical-softattn_additive-resume_roi-BS_96-cpu_8-LR_1e-4-epoch_100-skynet-seed_1
# exp_name: 20200427-torch1.5-baseline-softattn_additive-BS_32-cpu_8-LR_1e-4-epoch_100-riplw2_2080_2-seed_1
# exp_name: 20200430-torch1.5-cyclical-BS_48-cpu_8-LR_1e-4-epoch_100-riplw2_2080_3-seed_1
# exp_name: 20200430-torch1.5-cyclical-resume_embed_logit-BS_48-cpu_8-LR_1e-4-epoch_100-riplw2_2080_3-seed_1
# exp_name: 20200430-torch1.5-cyclical-resume_embed_logit-BS_48-cpu_8-LR_1e-4-epoch_100-riplw2_2080_3-seed_123
exp_name: 20200430-torch1.5-cyclical-resume_embed_logit-BS_48-cpu_8-LR_1e-4-epoch_100-riplw2_2080_3-seed_50

# id: '1'

seed: 50
densecap_verbose: True
disp_interval: 1

# evaluating options
language_eval: True
eval_obj_grounding: True
inference_only: True
resume: True
load_best_score: 1 # load from the best model

# language model
att_model: cyclical
num_layers: 1
seq_per_img: 1

# training setting
learning_rate: 0.0001
# learning_rate: 0.00005
optim: "adam"
max_epochs: 100
# batch_size: 240
# batch_size: 256 # OOM
# batch_size: 192  # dataloading is slow
# num_workers: 2
# batch_size: 64
batch_size: 48
num_workers: 8

cuda: True
mGPUs: True

# model
softattn_type: "additive"

embedding_vocab_plus_1: False

# cyclical training
train_decoder_only: False
resume_decoder_exp_name: 20200427-torch1.5-baseline-softattn_additive-BS_32-cpu_8-LR_1e-4-epoch_100-riplw2_2080_2-seed_1
resume_embed: 1
resume_logit: 1
resume_roi_extractor: 1

# localizer
# localizer_only_groundable: True
localizer_only_groundable: False

# loss weights
xe_loss_weight: 0.5
caption_consistency_loss_weight: 0.5

# smaller model
num_prop_per_frm: 100
t_attn_size: 480
rnn_size: 1024
input_encoding_size: 512
att_hid_size: 512
